import json
import sys
import os
import glob


def print_log(log_path):
    with open(log_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    if 'code_file' not in data:
        print(f"Skipping {log_path} (old log format, not generated by current agent.py)")
        return

    print("=" * 60)
    print(f"FILE: {data['code_file']}")
    print(f"RUN ID: {data['run_id']}")
    print(f"FINAL STATUS: {data['final_status'].upper()}")
    print("=" * 60)

    for attempt in data['attempts']:
        print(f"\n--- Attempt {attempt['attempt']} ---")
        if attempt['passed']:
            print("Result: PASSED")
            print(attempt.get('note', ''))
        else:
            print("Result: FAILED")
            # Show just the key error lines, not the full pytest wall of text
            error_lines = attempt['test_output'].split('\n')
            key_lines = [l for l in error_lines if 'assert' in l.lower() or 'Error' in l]
            if key_lines:
                print("Error summary:")
                for line in key_lines[:5]:
                    print(f"  {line.strip()}")

            if 'proposed_fix' in attempt:
                print("\nProposed fix:")
                print(attempt['proposed_fix'])

    print("\n" + "=" * 60 + "\n")


def main():
    if len(sys.argv) == 2:
        # View a specific log file
        print_log(sys.argv[1])
    else:
        # View all logs in order
        log_files = sorted(glob.glob('logs/*.json'))
        if not log_files:
            print("No logs found in logs/ folder.")
            return
        for log_file in log_files:
            print_log(log_file)


if __name__ == '__main__':
    main()